app/controllers/employees_controller.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from app.controllers.utils import extract_employees, filter_by_name_or_id
from app.ext.database import db
from app.ext.wtforms.forms import EmployeeForm, SearchForm
from app.models import Employee

ROWS_PER_PAGE = 9


employees = Blueprint("employees", __name__, template_folder="templates")


@employees.get("/employees")
def index():
    page = request.args.get("page", 1, type=int)
    search = request.args.get("search")
    form = SearchForm()

    query = Employee.query
    if search:
        query = filter_by_name_or_id(search)

    employees = query.order_by(Employee.name).paginate(
        page=page, per_page=ROWS_PER_PAGE
    )
    return render_template(
        "employees/employees.html",
        title="Employees",
        employees=employees,
        search=search,
        form=form,
    )


@employees.get("/employees/<int:id>")
def detail(id):
    employee = Employee.query.filter_by(id=id).first()
    return {"id": employee.id, "name": employee.name}


@employees.get("/employees/new")
def new():
    form = EmployeeForm()
    return render_template(
        "employees/employees_new.html", title="New Employee", form=form
    )


@employees.post("/employees/new_file")
def create_by_file():
    file = request.files["file"]
    if not file:
        flash("No file")
        return redirect(url_for("employees.index"))

    employees_data = extract_employees(file)

    try:
        employees = [Employee(**e_d) for e_d in employees_data]
        db.session.bulk_save_objects(employees)
        db.session.commit()
        flash("Succefull added Employees")
    except Exception as err:
        flash(f"{err.orig.args}")
        flash(f"Something Wrong - Invalid Data")
    finally:
        return redirect(url_for("employees.index"))


@employees.post("/employees/create")
def create():
    form = EmployeeForm()
    if not form.validate_on_submit():
        flash("Form not valid")
        return redirect(url_for("employees.new"))

    if Employee.query.filter_by(id=form.id.data).first():
        flash("Employee has exist")
        return render_template(
            "employees/employees_new.html", title="New Employee", form=form
        )

    employee = Employee(**form.employee)
    db.session.add(employee)
    db.session.commit()

    return redirect(url_for("employees.index"))


@employees.get("/employees/<int:id>/edit")
def edit(id):
    """Edit Employee"""
    employee = Employee.query.filter_by(id=id).first()

    form = EmployeeForm()
    form.employee = employee

    return render_template(
        "employees/employees_edit.html", title="Edit Employee", id=id, form=form
    )


@employees.post("/employees/<int:id>/update")
def update(id):
    """Process Edit route"""
    form = EmployeeForm()

    if form.validate_on_submit():
        Employee.query.filter_by(id=id).update(form.employee)
        db.session.commit()

    return redirect(url_for("employees.index"))


@employees.route("/employees/<int:id>/delete")
def delete(id):

    page = request.args.get("page", 1, type=int)
    search = request.args.get("search")

    Employee.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for("employees.index", page=page, search=search))

app/ext/blueprints/employees/views.py
from flask import Blueprint, flash, jsonify, render_template, redirect, request, url_for
from app.ext.wtforms.forms import EmployeeForm
from app.models import Employee, Company
from app.ext.database import db


employees = Blueprint('employees', __name__, template_folder='templates')

@employees.get('/employees')
def index():
    employees = Employee.query.all()
    return render_template('employees/employees.html', title='Employees', employees=employees)

@employees.get('/employees/<int:id>')
def detail(id):
    employee = Employee.query.filter_by(id=id).first()
    return jsonify({'id':employee.id, 'name':employee.name})

@employees.get('/employees/new')
def new():
    form = EmployeeForm()
    return render_template('employees/employees_new.html', title='New Employee', form=form)

@employees.post('/employees/create')
def create():
    form = EmployeeForm()
    if not form.validate_on_submit():
        flash('Form not valid')
        return redirect(url_for('employees.new'))
    id = form.id.data
    name = form.name.data
    company_id = form.companies.data

    if Employee.query.filter_by(id=id).first():
        flash('Employee has exist')
        return render_template('employees/employees_new.html', title='New Employee', form=form)
    employee = Employee(id=id, name=name, company_id=company_id)
    db.session.add(employee)
    db.session.commit()

    return redirect(url_for('employees.index'))

@employees.get('/employees/<int:id>/edit')
def edit(id):
    employee = Employee.query.filter_by(id=id).first()
    form = EmployeeForm()
    form.id.data = employee.id
    form.name.data = employee.name
    return render_template('employees/employees_edit.html', title='Edit Employee', id=id, form=form)

@employees.post('/employees/<int:id>/update')
def update(id):
    form = EmployeeForm()

    if Employee.query.filter_by(id=form.id.data).first():
        flash('Employee has exist')
        return render_template('employees/employees_edit.html', title='Edit Employee', id=request.form["current_id"], form=form)

    if form.validate_on_submit():
        employee = Employee.query.filter_by(id=request.form["current_id"]).first()
        employee.id = form.id.data
        employee.name = form.name.data
        db.session.add(employee)
        db.session.commit()

    return redirect(url_for('employees.index'))

@employees.route('/employees/<id>/delete')
def delete(id):
    Employee.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('employees.index'))

app/ext/views/employees/__init__.py
from .views import employees


def init_app(app):
    app.register_blueprint(employees)

app/ext/views/employees/views.py
from flask import Blueprint, flash, jsonify, render_template, redirect, request, url_for
from app.ext.wtforms.forms import EmployeeForm
from app.models import Employee, Company
from app.ext.database import db


employees = Blueprint('employees', __name__, template_folder='templates')

@employees.get('/employees')
def index():
    employees = Employee.query.all()
    return render_template('employees/employees.html', title='Employees', employees=employees)

@employees.get('/employees/<int:id>')
def detail(id):
    employee = Employee.query.filter_by(id=id).first()
    return jsonify({'id':employee.id, 'name':employee.name})

@employees.get('/employees/new')
def new():
    form = EmployeeForm()
    return render_template('employees/employees_new.html', title='New Employee', form=form)

@employees.post('/employees/create')
def create():
    form = EmployeeForm()
    if not form.validate_on_submit():
        flash('Form not valid')
        return redirect(url_for('employees.new'))
    id = form.id.data
    name = form.name.data
    war_name = form.war_name.data
    role = form.role.data
    identification = form.identification.data
    admission = form.admission.data
    company_id = form.company.data

    if Employee.query.filter_by(id=id).first():
        flash('Employee has exist')
        return render_template('employees/employees_new.html', title='New Employee', form=form)
    employee = Employee(id=id, name=name, company_id=company_id)
    db.session.add(employee)
    db.session.commit()

    return redirect(url_for('employees.index'))

@employees.get('/employees/<int:id>/edit')
def edit(id):
    employee = Employee.query.filter_by(id=id).first()
    form = EmployeeForm()
    form.id.data = employee.id
    form.name.data = employee.name
    return render_template('employees/employees_edit.html', title='Edit Employee', id=id, form=form)

@employees.post('/employees/<int:id>/update')
def update(id):
    form = EmployeeForm()

    if Employee.query.filter_by(id=form.id.data).first():
        flash('Employee has exist')
        return render_template('employees/employees_edit.html', title='Edit Employee', id=request.form["current_id"], form=form)

    if form.validate_on_submit():
        employee = Employee.query.filter_by(id=request.form["current_id"]).first()
        employee.id = form.id.data
        employee.name = form.name.data
        db.session.add(employee)
        db.session.commit()

    return redirect(url_for('employees.index'))

@employees.route('/employees/<id>/delete')
def delete(id):
    Employee.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('employees.index'))

app/templates/employees/employees.html
{% extends "template.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    {% if not employees %}
        <h2>No registered employees</h2>
    {% endif %}
    <div>
        <a class="btn btn-dark" href="{{ url_for('employees.new') }}">Add Employee</a>
        <a class="btn btn-danger" href="{{ url_for('home.index') }}">Back</a>
    </div>
    <form method="GET" action="{{ url_for('employees.index') }}">
        {{ form.csrf_token }}
        {{ form.search.label(class='h3', style='display: block') }}
        {{ form.search(class='form-control', style='display: inline-block; width: 30%') }}
        <input class="btn btn-dark" type="submit" value="Search">
    </form> 
    <table class="table table-striped table-responsive table-bordered">
        <thead class="thead-default">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Company</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.name }}</td>
                <td>{{ employee.company.name }}</td>
                <td>
                    <a class="btn btn-dark" href="{{ url_for('employees.edit', id=employee.id) }}">Edit</a>
                    <a class="btn btn-danger" href="{{ url_for('employees.delete', id=employee.id, page=employees.page, search=search) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <div style="position:absolute; right: 5%; bottom: 5%;">
        <a href="{{ url_for('employees.index', page=employees.prev_num, search=search) }}"
            class="btn btn-outline-dark 
            {% if employees.page == 1 %}disabled{% endif %}">
            &laquo;
        </a>
        <!-- Loop through the number of pages to display a link for each-->
        {% for page_num in employees.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
        <!-- Check for the active page and set the link to "Active"-->
                {% if employees.page == page_num %}
                <a href="{{ url_for('employees.index', page=page_num, search=search) }}"
                    class="btn btn-dark">
                    {{ page_num }}
                </a>
                {% else %}
                <a href="{{ url_for('employees.index', page=page_num, search=search) }}"
                    class="btn btn-outline-dark">
                    {{ page_num }}
                </a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        <a href="{{ url_for('employees.index', page=employees.next_num, search=search) }}"
            class="btn btn-outline-dark 
            {% if employees.page == employees.pages %}disabled{% endif %}">
            &raquo;
        </a>
    </div>
    <p style="position: absolute; right: 5%; bottom: 0;" class="mt-5">
        Showing page {{ employees.page }} of {{ employees.pages }}
    </p>
{% endblock %}

app/templates/employees/employees_edit.html
{% extends "template.html" %}
{% block content %}
<h1>{{ title }}</h1>
<form class="formObjects" action="{{ url_for('employees.update', id=id) }}" method="POST" enctype="multipart/form-data">
    <fieldset>
        {{ form.csrf_token() }}
        {{ form.id(class='form-control', type='hidden', value=id) }}
        <div class="form-group inputBox">
            {{ form.name.label(class='form-label') }}
            {{ form.name(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.war_name.label(class='form-label') }}
            {{ form.war_name(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.role.label(class='form-label') }}
            {{ form.role(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.identification.label(class='form-label') }}
            {{ form.identification(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.admission.label(class='form-label') }}
            {{ form.admission(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.company.label(class='form-label') }}
            {{ form.company(class='input-block') }}
        </div>
        <div class="form-group">
            {{ form.to_print.label(class='form-label') }}
            {{ form.to_print() }}
        </div>
        <div class="form-group buttons">
            {{ form.save(class='btn btn-dark') }}
            <a class="btn btn-danger" href="{{ url_for('employees.index') }}">Back</a>
        </div>
    </fieldset>
</form>
{% endblock %}

app/templates/employees/employees_new.html
{% extends "template.html" %}
{% block content %}
<h1>{{ title }}</h1>
<form class="formObjects" action="{{ url_for('employees.create_by_file') }}" method="POST" enctype="multipart/form-data">
    {{ form.csrf_token() }}
    <input type="file" name="file" accept=".xlsx">
    <input class="btn btn-dark" type="submit">
</form> 
<form class="formObjects" action="{{ url_for('employees.create') }}" method="POST" enctype="multipart/form-data">
    <fieldset>
        {{ form.csrf_token() }}
        <div class="form-group inputBox">
            {{ form.id.label(class='form-label') }}
            {{ form.id(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.name.label(class='form-label') }}
            {{ form.name(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.war_name.label(class='form-label') }}
            {{ form.war_name(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.role.label(class='form-label') }}
            {{ form.role(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.identification.label(class='form-label') }}
            {{ form.identification(class='form-control') }}
        </div>
        <div class="form-group inputBox">
            {{ form.admission.label(class='form-label') }}
            {{ form.admission(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.company.label(class='form-label') }}
            {{ form.company(class='input-block') }}
        </div>
        <div class="form-group">
            {{ form.to_print.label(class='form-label') }}
            {{ form.to_print() }}
        </div>
        <div class="form-group buttons">
            {{ form.save(class='btn btn-dark') }}
            <a class="btn btn-danger" href="{{ url_for('employees.index') }}">Back</a>
        </div>
    </fieldset>
</form>
{% endblock %}