app/controllers/checkout_controller.py
import csv
from flask import Blueprint, render_template, request, send_file
from app.models import Employee

from datetime import datetime
ROWS_PER_PAGE = 15


checkout = Blueprint("checkout", __name__, template_folder="templates")


@checkout.get("/checkout")
def index():
    """Show All employees to print."""
    page = request.args.get("page", 1, type=int)

    query = Employee.query.filter_by(to_print=True).order_by(Employee.name)
    employees = query.paginate(page=page, per_page=ROWS_PER_PAGE)
    return render_template(
        "checkout/checkout.html", title="Checkout", employees=employees
    )


@checkout.get("/checkout/download_front/")
def download_front():
    """Create and download front file based on employees to print"""
    employees = Employee.query.filter_by(to_print=True).all()

    with open("app/tmp/front.csv", "w", encoding="UTF8", newline="") as file:
        data = file_front(employees)
        writer = csv.writer(file)
        writer.writerows(data)

    return send_file(
        "tmp/front.csv",
        mimetype="text/csv",
        download_name="front.csv",
        as_attachment=True,
    )


@checkout.get("/checkout/download_back/")
def download_back():
    """Create and download back file based on employees to print"""
    employees = Employee.query.filter_by(to_print=True).all()

    with open("app/tmp/back.csv", "w", encoding="UTF8", newline="") as file:
        data = file_back(employees)
        writer = csv.writer(file)
        writer.writerows(data)

    return send_file(
        "tmp/back.csv",
        mimetype="text/csv",
        download_name="back.csv",
        as_attachment=True,
    )


def file_front(employees) -> str:
    data = [["matricula", "nome_guerra", "cargo", "lotacao", "foto", "mostrar_foto"]]
    for employee in employees:
        data.append(
            [
                employee.id,
                employee.war_name,
                employee.role,
                employee.company.name,
                f"C:/Users/Mareg/OneDrive/Maré Gráfica/Clientes/LAP/Crachás/Orgaos/{employee.company.name}/fotos/3x4/{employee.id}.jpg",
                "True",
            ]
        )
    return data


def file_back(employees) -> str:
    data = [["matricula", "nome", "identidade", "admissao"]]
    for employee in employees:
        id = employee.identification
        cpf = '{}.{}.{}-{}'.format(id[:3], id[3:6], id[6:9], id[9:])
        date_time = datetime.fromisoformat(employee.admission)
        date = date_time.strftime("%d/%m/%Y")

        data.append(
            [employee.id, employee.name, cpf, date]
        )
    return data

app/controllers/home_controller.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models import Employee
from app.ext.wtforms.forms import SearchForm
from app.ext.database import db
from app.controllers.utils import filter_by_name_or_id

ROWS_PER_PAGE = 9


home = Blueprint("home", __name__, template_folder="templates")


@home.get("/")
def index():
    page = request.args.get("page", 1, type=int)
    search = request.args.get("search")
    form = SearchForm(request.args, meta={"csrf": False})

    query = Employee.query
    if search:
        query = filter_by_name_or_id(search)

    employees = query.order_by(Employee.name).paginate(
        page=page, per_page=ROWS_PER_PAGE
    )
    return render_template(
        "home/home.html",
        title="ID Card Manager",
        employees=employees,
        search=search,
        form=form,
    )

@home.get('/not-to-print/')
def not_to_print():
    for employee in Employee.query.all():
        employee.to_print = False
    db.session.commit()
    return redirect(url_for('home.index'))

@home.get("/<int:id>/")
def switch_print(id):
    page = request.args.get("page", 1, type=int)
    search = request.args.get("search", type=str)

    employee = Employee.query.get(id)
    employee.to_print = not employee.to_print
    db.session.add(employee)
    db.session.commit()
    return redirect(url_for("home.index", page=page, search=search))

app/ext/controllers/home/__init__.py
from .views import home


def init_app(app):
    app.register_blueprint(home)

app/templates/home/home.html
{% extends "template.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <div>
        <a class="btn btn-dark" href="{{ url_for('employees.index') }}">Employees</a>
        <a class="btn btn-dark" href="{{ url_for('companies.index') }}">Companies</a>
        <a class="btn btn-dark" href="{{ url_for('checkout.index') }}">Checkout</a>
        <a class="btn btn-danger" href="{{ url_for('home.not_to_print') }}">Set all not to print</a>
    </div>
    <form method="GET" action="{{ url_for('home.index') }}">
        {{ form.csrf_token }}
        {{ form.search.label(class='h3', style='display: block') }}
        {{ form.search(class='form-control', style='display: inline-block; width: 30%') }}
        <input class="btn btn-dark" type="submit" value="Search">
    </form> 
    <table class="table table-striped table-responsive table-bordered">
        <thead class="thead-default">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Company</th>
                <th>To Print</th>
            </tr>
        </thead>
        <tbody>
            {% if not employees %}
            <h2>No registered employees</h2>
            {% endif %}
            {% for employee in employees.items %}
            {% if employee.to_print %}
            <tr style="background-color: lightgreen;">
            {% else %}
            <tr style="background-color: lightpink;">
            {% endif %}
                <td>{{ employee.id }}</td>
                <td>{{ employee.name }}</td>
                <td>{{ employee.company.name }}</td>
                <td>
                    {% if employee.to_print %}
                    <a class="btn btn-danger" href="{{ url_for('home.switch_print', id=employee.id, page=employees.page, search=search) }}">Cancel</a>
                    {% else %}
                    <a class="btn btn-success" href="{{ url_for('home.switch_print', id=employee.id, page=employees.page, search=search) }}">Print</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <div style="position:absolute; right: 5%; bottom: 5%;">
        <a href="{{ url_for('home.index', page=employees.prev_num, search=search) }}"
            class="btn btn-outline-dark 
            {% if employees.page == 1 %}disabled{% endif %}">
            &laquo;
        </a>
        <!-- Loop through the number of pages to display a link for each-->
        {% for page_num in employees.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
        <!-- Check for the active page and set the link to "Active"-->
                {% if employees.page == page_num %}
                <a href="{{ url_for('home.index', page=page_num, search=search) }}"
                    class="btn btn-dark">
                    {{ page_num }}
                </a>
                {% else %}
                <a href="{{ url_for('home.index', page=page_num, search=search) }}"
                    class="btn btn-outline-dark">
                    {{ page_num }}
                </a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        <a href="{{ url_for('home.index', page=employees.next_num, search=search) }}"
            class="btn btn-outline-dark 
            {% if employees.page == employees.pages %}disabled{% endif %}">
            &raquo;
        </a>
    </div>
    <p style="position: absolute; right: 5%; bottom: 0;" class="mt-5">
        Showing page {{ employees.page }} of {{ employees.pages }}
    </p>
{% endblock %}