app/controllers/checkout_controller.py
import csv
from flask import Blueprint, render_template, request, send_file
from app.models import Employee

from datetime import datetime
ROWS_PER_PAGE = 15


checkout = Blueprint("checkout", __name__, template_folder="templates")


@checkout.get("/checkout")
def index():
    """Show All employees to print."""
    page = request.args.get("page", 1, type=int)

    query = Employee.query.filter_by(to_print=True).order_by(Employee.name)
    employees = query.paginate(page=page, per_page=ROWS_PER_PAGE)
    return render_template(
        "checkout/checkout.html", title="Checkout", employees=employees
    )


@checkout.get("/checkout/download_front/")
def download_front():
    """Create and download front file based on employees to print"""
    employees = Employee.query.filter_by(to_print=True).all()

    with open("app/tmp/front.csv", "w", encoding="UTF8", newline="") as file:
        data = file_front(employees)
        writer = csv.writer(file)
        writer.writerows(data)

    return send_file(
        "tmp/front.csv",
        mimetype="text/csv",
        download_name="front.csv",
        as_attachment=True,
    )


@checkout.get("/checkout/download_back/")
def download_back():
    """Create and download back file based on employees to print"""
    employees = Employee.query.filter_by(to_print=True).all()

    with open("app/tmp/back.csv", "w", encoding="UTF8", newline="") as file:
        data = file_back(employees)
        writer = csv.writer(file)
        writer.writerows(data)

    return send_file(
        "tmp/back.csv",
        mimetype="text/csv",
        download_name="back.csv",
        as_attachment=True,
    )


def file_front(employees) -> str:
    data = [["matricula", "nome_guerra", "cargo", "lotacao", "foto", "mostrar_foto"]]
    for employee in employees:
        data.append(
            [
                employee.id,
                employee.war_name,
                employee.role,
                employee.company.name,
                f"C:/Users/Mareg/OneDrive/Maré Gráfica/Clientes/LAP/Crachás/Orgaos/{employee.company.name}/fotos/3x4/{employee.id}.jpg",
                "True",
            ]
        )
    return data


def file_back(employees) -> str:
    data = [["matricula", "nome", "identidade", "admissao"]]
    for employee in employees:
        id = employee.identification
        cpf = '{}.{}.{}-{}'.format(id[:3], id[3:6], id[6:9], id[9:])
        date_time = datetime.fromisoformat(employee.admission)
        date = date_time.strftime("%d/%m/%Y")

        data.append(
            [employee.id, employee.name, cpf, date]
        )
    return data

app/controllers/employees_controller.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from app.controllers.utils import extract_employees, filter_by_name_or_id
from app.ext.database import db
from app.ext.wtforms.forms import EmployeeForm, SearchForm
from app.models import Employee

ROWS_PER_PAGE = 9


employees = Blueprint("employees", __name__, template_folder="templates")


@employees.get("/employees")
def index():
    page = request.args.get("page", 1, type=int)
    search = request.args.get("search")
    form = SearchForm()

    query = Employee.query
    if search:
        query = filter_by_name_or_id(search)

    employees = query.order_by(Employee.name).paginate(
        page=page, per_page=ROWS_PER_PAGE
    )
    return render_template(
        "employees/employees.html",
        title="Employees",
        employees=employees,
        search=search,
        form=form,
    )


@employees.get("/employees/<int:id>")
def detail(id):
    employee = Employee.query.filter_by(id=id).first()
    return {"id": employee.id, "name": employee.name}


@employees.get("/employees/new")
def new():
    form = EmployeeForm()
    return render_template(
        "employees/employees_new.html", title="New Employee", form=form
    )


@employees.post("/employees/new_file")
def create_by_file():
    file = request.files["file"]
    if not file:
        flash("No file")
        return redirect(url_for("employees.index"))

    employees_data = extract_employees(file)

    try:
        employees = [Employee(**e_d) for e_d in employees_data]
        db.session.bulk_save_objects(employees)
        db.session.commit()
        flash("Succefull added Employees")
    except Exception as err:
        flash(f"{err.orig.args}")
        flash(f"Something Wrong - Invalid Data")
    finally:
        return redirect(url_for("employees.index"))


@employees.post("/employees/create")
def create():
    form = EmployeeForm()
    if not form.validate_on_submit():
        flash("Form not valid")
        return redirect(url_for("employees.new"))

    if Employee.query.filter_by(id=form.id.data).first():
        flash("Employee has exist")
        return render_template(
            "employees/employees_new.html", title="New Employee", form=form
        )

    employee = Employee(**form.employee)
    db.session.add(employee)
    db.session.commit()

    return redirect(url_for("employees.index"))


@employees.get("/employees/<int:id>/edit")
def edit(id):
    """Edit Employee"""
    employee = Employee.query.filter_by(id=id).first()

    form = EmployeeForm()
    form.employee = employee

    return render_template(
        "employees/employees_edit.html", title="Edit Employee", id=id, form=form
    )


@employees.post("/employees/<int:id>/update")
def update(id):
    """Process Edit route"""
    form = EmployeeForm()

    if form.validate_on_submit():
        Employee.query.filter_by(id=id).update(form.employee)
        db.session.commit()

    return redirect(url_for("employees.index"))


@employees.route("/employees/<int:id>/delete")
def delete(id):

    page = request.args.get("page", 1, type=int)
    search = request.args.get("search")

    Employee.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for("employees.index", page=page, search=search))

app/ext/views/checkout/__init__.py
from .views import checkout


def init_app(app):
    app.register_blueprint(checkout)

app/ext/views/checkout/views.py
from flask import Blueprint, flash, jsonify, render_template, redirect, request, url_for
from app.ext.wtforms.forms import EmployeeForm
from app.models import Employee, Company
from app.ext.database import db


checkout = Blueprint('checkout', __name__, template_folder='templates')

@checkout.get('/checkout')
def index():
    employees = Employee.query.filter_by(for_print=False).all()
    return render_template('checkout/checkout.html', title='Checkout', employees=employees)

app/templates/checkout/checkout.html
{% extends "template.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    {% if not employees %}
        <h2>No employees to print</h2>
    {% endif %}
    <div>
        <a class="btn btn-danger" href="{{ url_for('home.index') }}">Back</a>
        <h2>Download Files:</h2>
        <a class="btn btn-dark" href="{{ url_for('checkout.download_front') }}">front.csv</a>
        <a class="btn btn-dark" href="{{ url_for('checkout.download_back') }}">back.csv</a>
    </div>
    <table class="table table-striped table-responsive table-bordered">
        <thead class="thead-default">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Company</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.name }}</td>
                <td>{{ employee.company.name }}</td>
                <td>
                    <!-- <a class="btn btn-danger" href="{{ url_for('employees.delete', id=employee.id) }}">Remove</a> -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div style="position:absolute; right: 5%; bottom: 5%;">
        <a href="{{ url_for('checkout.index', page=employees.prev_num) }}"
            class="btn btn-outline-dark 
            {% if employees.page == 1 %}disabled{% endif %}">
            &laquo;
        </a>
        <!-- Loop through the number of pages to display a link for each-->
        {% for page_num in employees.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        <!-- Check for the active page and set the link to "Active"-->
                {% if employees.page == page_num %}
                <a href="{{ url_for('checkout.index', page=page_num) }}"
                    class="btn btn-dark">
                    {{ page_num }}
                </a>
                {% else %}
                <a href="{{ url_for('checkout.index', page=page_num) }}"
                    class="btn btn-outline-dark">
                    {{ page_num }}
                </a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        <a href="{{ url_for('checkout.index', page=employees.next_num) }}"
            class="btn btn-outline-dark 
            {% if employees.page == employees.pages %}disabled{% endif %}">
            &raquo;
        </a>
        </div>
        <p style="position: absolute; right: 5%; bottom: 0;" class="mt-5">
        Showing page {{ employees.page }} of {{ employees.pages }}
        </p>
{% endblock %}