app/controllers/companies_controller.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for
from app.ext.database import db
from app.ext.wtforms.forms import CompanyForm
from app.models import Company

companies = Blueprint("companies", __name__, template_folder="templates")


@companies.get("/companies")
def index():
    companies = Company.query.all()
    return render_template(
        "companies/companies.html", title="Companies", companies=companies
    )


@companies.get("/companies/<int:id>")
def detail(id):
    company = Company.query.filter_by(id=id).first()
    return jsonify({"id": company.id, "name": company.name})


@companies.get("/companies/new")
def new():
    form = CompanyForm()
    return render_template(
        "companies/companies_new.html", title="New Company", form=form
    )


@companies.post("/companies/create")
def create():
    form = CompanyForm(request.form)
    if not form.validate_on_submit():
        return redirect(url_for("companies.new"))
    name = form.name.data
    try:
        company = Company(name=name)
    except:
        return redirect(url_for("companies.index"))
    db.session.add(company)
    db.session.commit()
    return redirect(url_for("companies.index"))


@companies.get("/companies/<int:id>/edit")
def edit(id):
    employee = Company.query.filter_by(id=id).first()
    form = CompanyForm()
    form.id.data = employee.id
    form.name.data = employee.name
    return render_template(
        "companies/companies_edit.html", title="Edit Company", id=id, form=form
    )


@companies.post("/companies/<int:id>/update")
def update(id):
    form = CompanyForm(request.form)
    if form.validate_on_submit():
        company = Company.query.filter_by(id=request.form["current_id"]).first()
        company.name = form.name.data
        db.session.add(company)
        db.session.commit()

    return redirect(url_for("companies.index"))


@companies.route("/companies/<id>/delete")
def delete(id):
    Company.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for("companies.index"))

app/ext/views/companies/__init__.py
from .views import companies


def init_app(app):
    app.register_blueprint(companies)

app/ext/views/companies/views.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for
from app.models import Company
from app.ext.wtforms.forms import CompanyForm
from app.ext.database import db

companies = Blueprint('companies', __name__, template_folder='templates')

@companies.get('/companies')
def index():
    companies = Company.query.all()
    return render_template('companies/companies.html', title='Companies', companies=companies)

@companies.get('/companies/<int:id>')
def detail(id):
    company = Company.query.filter_by(id=id).first()
    return jsonify({'id':company.id, 'name':company.name})

@companies.get('/companies/new')
def new():
    form = CompanyForm()
    return render_template('companies/companies_new.html', title='New Company', form=form)

@companies.post('/companies/create')
def create():
    form = CompanyForm(request.form)
    if not form.validate_on_submit():
        return redirect(url_for('companies.new'))
    name = form.name.data
    try:
        company = Company(name=name)
    except:
        return redirect(url_for('companies.index'))
    db.session.add(company)
    db.session.commit()
    return redirect(url_for('companies.index'))

@companies.get('/companies/<int:id>/edit')
def edit(id):
    employee = Company.query.filter_by(id=id).first()
    form = CompanyForm()
    form.id.data = employee.id
    form.name.data = employee.name
    return render_template('companies/companies_edit.html', title='Edit Company', id=id, form=form)

@companies.post('/companies/<int:id>/update')
def update(id):
    form = CompanyForm(request.form)
    if form.validate_on_submit():
        company = Company.query.filter_by(id=request.form["current_id"]).first()
        company.name = form.name.data
        db.session.add(company)
        db.session.commit()

    return redirect(url_for('companies.index'))

@companies.route('/companies/<id>/delete')
def delete(id):
    Company.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('companies.index'))

app/templates/companies/companies.html
{% extends "template.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <div>
        <a class="btn btn-dark" href="{{ url_for('companies.new') }}">Add Company</a>
        <a class="btn btn-danger" href="{{ url_for('home.index') }}">Back</a>
    </div>
    {% if not companies %}
        <h2>No registered companies</h2>
    {% endif %}
    <table class="table table-striped table-responsive table-bordered">
        <thead class="thead-default">
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for company in companies %}
            <tr>
                <td>{{ company.id }}</td>
                <td>{{ company.name }}</td>
                <td>
                    <a class="btn btn-dark" href="{{ url_for('companies.edit', id=company.id) }}">Edit</a>
                    <a class="btn btn-danger" href="{{ url_for('companies.delete', id=company.id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/companies/companies_edit.html
{% extends "template.html" %}
{% block content %}
<h1>{{ title }}</h1>
<form class="formObjects" action="{{ url_for('companies.update', id=id) }}" method="POST" enctype="multipart/form-data">
    <fieldset>
        <input type="hidden" name="current_id" value="{{ id }}">
        {{ form.csrf_token() }}
        <div class="form-group inputBox">
            {{ form.name.label(class='form-label') }}
            {{ form.name(class='form-control') }}
        </div>
        <div class="form-group buttons">
            {{ form.save(class='btn btn-dark') }}
            <a class="btn btn-danger" href="{{ url_for('companies.index') }}">Back</a>
        </div>
    </fieldset>
</form>
{% endblock %}

app/templates/companies/companies_new.html
{% extends "template.html" %}
{% block content %}
<h1>{{ title }}</h1>
<form class="formObjects" action="{{ url_for('companies.create') }}" method="POST" enctype="multipart/form-data">
    <fieldset>
        {{ form.csrf_token() }}
        <div class="form-group inputBox">
            {{ form.name.label(class='form-label') }}
            {{ form.name(class='form-control') }}
        </div>
        <div class="form-group buttons">
            {{ form.save(class='btn btn-dark') }}
            <a class="btn btn-danger" href="{{ url_for('companies.index') }}">Back</a>
        </div>
    </fieldset>
</form>
{% endblock %}